trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npx playwright install --with-deps
    displayName: 'Install Playwright browsers'

  - script: |
      npx playwright test --reporter=html
    displayName: 'Run Playwright tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results/*.xml'
      failTaskOnFailedTests: true
    displayName: 'Publish test results'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report'
      artifactName: 'playwright-report'
    condition: succeededOrFailed()
    displayName: 'Publish Playwright HTML report'