version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:15-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install
          command: npm install

      - run:
          name: Install playwright cli
          command: npx playwright install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: 
          name: Run API test
          command: npm run test-api

      - run: 
          name: Run E2E test
          command: npm run test-e2e

      - run: 
          name: Generate allure report
          command: npm run allure-report      
           
      - store_artifacts:
          path: /home/circleci/repo/allure-report

      - store_artifacts:
          path: /home/circleci/repo/logs       